name: 🍀 기타 항목
description: 기타 작업을 하는 경우, 이 템플릿을 사용해 주세요!
title: "🍀 Chore: "
labels: ["Chore 🍀"]
body:
  - type: markdown
    attributes:
      value: "이슈를 작성하기 전, 다음 사항을 고려해 주세요.\n- [ ] Assignees에 담당자를 지정해 주세요. 아직 없는 경우에는 비워주세요.\n- [ ] Labels에 이슈의 종류와 담당자를 지정해 주세요. 아직 없는 경우에는 비워주세요"
  - type: textarea
    id: description
    attributes:
      label: 🏷️ Description
      description: 이슈에 대한 설명을 적어주세요.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: todo
    attributes:
      label: 🦁 TODO
      description: 이 이슈를 진행하기 위해 어떤 작업이 필요한가요?
      placeholder: -[ ] 그래프 그려요
      value: "- [ ] "
    validations:
      required: false
  - type: textarea
    id: branch
    attributes:
      label: 🦁 Branch Name
      description: 해당 이슈와 관련된 작업을 진행할 브랜치명을 작성해 주세요.
      value: "chore/#?-"
    validations:
      required: false
